### ISSUE TITLE
Repeat search cannot be started

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#892] opened 2023-03-01 09:22 UTC
**Describe the bug**
When trying to start a repeat search based on the API specs I receive a "500 internal server error". 

The logs show the following: Object reference not set to an instance of an object.

**To Reproduce**
Start a repeat search in dev system

**Expected behaviour**
200 OK and repeat search starts

**Comment by seanmobrien** [comment] 2023-03-03 21:52
An example of the ArgNullException thrown by repeat search can be found at https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%2260c8f25e-3072-408e-ad80-e16d3656fdd7%22%2C%22ResourceGroup%22%3A%22WMDA-DEV-ATLAS-RESOURCE-GROUP%22%2C%22Name%22%3A%22WMDA-DEV-ATLAS%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F60c8f25e-3072-408e-ad80-e16d3656fdd7%252FresourceGroups%252FWMDA-DEV-ATLAS-RESOURCE-GROUP%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252FWMDA-DEV-ATLAS%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22d27def59-b9d3-11ed-85c5-05e0dd4058c2%22%2C%22timestamp%22%3A%222023-03-03T14%3A57%3A44.204Z%22%2C%22cacheId%22%3A%222e7bfdb6-901a-438d-b156-f350eedf1a8c%22%2C%22eventTable%22%3A%22exceptions%22%7D .  The error occurs because the storage container name and result file name values are null / empty.   A message shows up on the matching-results-ready/repeat-search subscription's dead letter queue when this occurs.  The message usually has a WasSuccessful value of false and a null BlobStorageContainerName/ResultsFileName value.

![Snag_6b2f905](https://user-images.githubusercontent.com/8743939/222836537-e3acfc37-b85b-40e0-b561-d44c406d8aaf.png)

**Comment by seanmobrien** [comment] 2023-03-07 17:57
Root cause of issue identified as a malformed repeat search request - input was missing the searchRequest wrapper.  Closing unless/until additional repeat search issues are identified

**Closed by seanmobrien** 2023-03-07 17:57 UTC
Labels: bug, wmda-mvp
