### ISSUE TITLE
differences in donors returned compared to HAP-E and optimas

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#698] opened 2022-03-18 10:55 UTC
When performing searches in HAP-E, Optimas and ATLAS there is a significant difference between ATLAS and Optimas/HAP-E. 

This needs to be investigated. 

One example is 0 search results for ATLAS whereas HAP-E has 71 and Optimas 65. I have done some tests and the donors seem to be present in the ATLAS DB, but are somehow not returned

**Comment by benbelow** [comment] 2022-03-18 11:03
@mmelchers and I are sharing HLA information privately for this case, for data privacy reasons. If any conclusions are drawn, either about bugs in Atlas or differences in the algorithmic logic of the algorithms, I'll update this ticket

**Comment by benbelow** [comment] 2022-03-18 13:21
We've confirmed through investigation that this difference was due to a typo in the patient data used for this search. @mmelchers  is going to re-run the test searches. I'll close this issue, we can re-open if we start to see discrepancies after fixing the typo

**Closed by benbelow** 2022-03-18 13:21 UTC
Labels: wmda-mvp, investigation
