### ISSUE TITLE
Data refresh is not successful

### ISSUE THREAD

**Issue by mmelchers** [Anthony-Nolan/Atlas#684] opened 2022-02-11 11:11 UTC
As a Product Owner I expect that all actions that are triggered automatically or manually are successful.

When I check the table [MatchingAlgorithmPersistent].[DataRefreshHistory]
then I see that since the 19th of July 2021 there has not been a successful data refresh. 

This should be fixed and should work consistently.

**Comment by benbelow** [comment] 2022-03-18 09:26
I've had a quick look at the logs for this data refresh: 

`DATA REFRESH: Refresh failed. Exception: Microsoft.Data.SqlClient.SqlException (0x80131904): Database 'testing-atlas-matching-a' on server 'testing-atlas-sql-server.database.windows.net' is not currently available.  Please retry the connection later. `

This looks like an issue with database auto-pause - the automated database scaling in the data refresh does not seem to cope well with auto-pause databases.

We could do some work on this, but I'm wary that as auto-pause databases won't be used in a live scenario, this doesn't need to be considered as necessary work for an MVP instance of Atlas.

@mmelchers please could you advise on your thoughts here?

**Comment by mmelchers** [comment] 2022-03-23 07:02
In my view, a proper setup requires a prod environment, a non-prod environment and a dev environment. 
-Production environment: full resources, no testing done. Should be most stable version
-Non-prod environment ("staging"/"pre-production"). As much as possible the same settings as production, but just  scaled down. This is where regression and UAT would take place. 
-Development version. This is where internal testing of new features takes place

In this case both Prod and non-prod would need to not have autopausing databases. That also means that we cannot test whether data refresh works well until we have setup the non-prod environment. I would much rather see the data refresh process be able to deal with a paused database, but it is not a requirement. It does mean that I cannot be certain that the data refresh works for us until the non-prod environment has been setup.

**Comment by benbelow** [comment] 2022-03-25 08:21
@mmelchers I don't think the following is quite accurate: 

> It does mean that I cannot be certain that the data refresh works for us until the non-prod environment has been setup.

Can I suggest that you: 

* Modify your test database to disable auto pause
* Run a data refresh, to test that this will work as expected
* Modify the database again when you're done to re-enable auto-pause

**Comment by mmelchers** [comment] 2022-03-25 08:45
Hi @benbelow , I can give that a try. Yesterday I performed a test by "waking up" both matching databases. I then confirmed that both A and B are online. I then started the data refresh but it still seems to have failed. it was at a different time point though. WasSuccessful is still set to null. 

Is it safe for me to do the above-mentioned steps in order to test data refresh without auto-pause? Or will the stuck data refresh interfere with it?

**Comment by benbelow** [comment] 2022-03-25 09:18
The stuck data refresh will need to be cleared up first - there's a cleanup function `RunDataRefreshCleanup` that automates the relevant database scaling and data cleanup, which will need to be run before triggering the data refresh again.

**Comment by benbelow** [comment] 2022-04-06 11:45
@mmelchers confirmed this morning that the data refresh has since run successfully. 

As such are you happy for me to close this bug issue?

**Comment by mmelchers** [comment] 2023-03-01 12:40
data refresh seems to work. Was recently performed by Sean. If there are any remaining issues. These can be handled in a new bug ticket.

**Closed** 2023-03-01 12:40 UTC
Labels: bug, wmda-mvp, matching-algorithm
