### ISSUE TITLE
Classic Application Insights is deprecated and will be retired in February 2024

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#1118] opened 2023-11-11 19:00 UTC
Can migrate in a few clicks on portal, but what about terraform? do we need to upgrade our App.I definitions?

https://learn.microsoft.com/en-gb/azure/azure-monitor/app/convert-classic-resource

Further info:
- The implication of migrating an existing resource is that all existing data will be gone.
- So it would be safer to create new Workspace-based Application Insights - need terraform definition for that
- Should not destroy the old AI instance as part of this ticket, else we will lose the data on release
- Will create new tickets to cover deletion of the old instance and also updating of any live azure alerts that depend on AI

**Comment by zabeen** [comment] 2024-01-08 11:54
@SergeyEzh Can you please investigate what changes we need to do here to migrate Atlas application insights via terraform? Thanks!

**Comment by SergeyEzh** [comment] 2024-01-15 11:35
@zabeen , As far I understand, we only need create Log Analytics Workspace and assign this workspace to existing Application Insights instance to migrate it. I've created draft PR, take a look at changes in application_insights.tf.

However, azurerm v3.36.0 can't assign workspace_id to application insights without recreating it, so the rest of the PR related to upgrade azrerm to newest version. There's one issue with upgrade: you can see that there is change how dotnet version is specified for function apps. And when I execute `terraform plan`, I see weird changes like that:

![Image](https://github.com/Anthony-Nolan/Atlas/assets/151528303/7f336cdd-c793-4bdf-a2e0-85a094b80854)

I think that it is not big issue, v4.0 is a default value and perhaps it thinks that previous value is v4.0 because it can't parse anymore previous value '6' stored in terraform state file. But I think I need opinion another person on that.

PS. If we don't upgrade azurerm, terrafrom plan is just going to recreate application insights resource. Which would be fine, but old logs will be lost.

**Comment by zabeen** [comment] 2024-01-23 09:42
### Testing Notes

- @zabeen 
  - check that AI instance still exists on dev (update in place by terraform) and that logs have not been lost. 
  - check that query used in alerts still work

- @DmitriyShcherbina 
  - Run regression for search 10/10 match prediction on & repeat search for new donor

**Comment by zabeen** [comment] 2024-01-23 10:13
### Infrastructure Testing

- Terraform updated AI resource in place (no destroy/create), and new workplace ID was assigned:
```
2024-01-23T09:50:47.6289630Z 1m  # azurerm_application_insights.atlas0m will be updated in-place0m0m
2024-01-23T09:50:47.6290382Z 0m  33m~0m0m resource "azurerm_application_insights" "atlas" {
2024-01-23T09:50:47.6291558Z         1m0mname0m0m                                  = "DEV-ATLAS"
2024-01-23T09:50:47.6291922Z         1m0mtags0m0m                                  = {}
2024-01-23T09:50:47.6292324Z       32m+0m 0m1m0mworkspace_id0m0m                          = (known after apply)
2024-01-23T09:50:47.6292709Z         90m# (15 unchanged attributes hidden)0m0m
2024-01-23T09:50:47.6292913Z 
2024-01-23T09:50:47.6293224Z         90m# (1 unchanged block hidden)0m0m
2024-01-23T09:50:47.6293480Z     }
```

- Looks like table schema on new workspace logs is different to classic AI, so existing queries will need to be updated.

**Comment by DmitriyShcherbina** [comment] 2024-01-23 12:06
@zabeen Regression testing status: Ok


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/c3879ddd-def2-47ba-98d9-52ace1040290)

![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/eed7d954-71ae-4a02-ac30-d07244339c88)

**Comment by zabeen** [comment] 2024-01-23 13:06
### Log Query Testing

- Old AI instance did not have any logs on the above search.
- New workspace did have logs for the search, that could be found via query: `AppTraces | where Properties["SearchRequestId"] == "05f458fa-cefd-4d78-bf8f-5354f4e2c227"`

**Closed** 2024-02-20 17:26 UTC
Labels: infrastructure, support
