### ISSUE TITLE
Do not expand / calculate genotype likelihoods multiple times for patient in match prediction batch

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#690] opened 2022-03-04 16:03 UTC
The three main time consuming steps of match prediction for a given patient/donor pair are: 

* Expanding to diplotypes
* Calculating likelihoods for all diplotypes
* Calculating match counts of diplotypes pairs

The first two of these stages will always be identical for the same patient - so for a particularly ambiguous patient, we will be potentially be performing expensive   yet identical work many times!

To some extent this is unavoidable, due to the horizontal scaling of the MPA, but it would be nice to cut down the time a bit by not repeating this work. 

We should be careful caching this data, as it can be as many as millions of possible diplotypes, which might take a bit much memory to persistently cache. We could look into just sharing it per batch - or perhaps cache with a fairly short lifespan to allow multiple parallel batches on the same cloud machine to benefit.

**Comment by benbelow** [comment] 2022-03-04 16:49
Potentially just storing the truncated version would be a way to save significant memory and allow caching of this data to be more reasonable!

**Comment by zabeen** [comment] 2024-04-03 12:43
Duplicate of #1131 which will apply to both patients and donors

**Closed by zabeen** 2024-04-03 12:43 UTC
Labels: match-prediction-algorithm, performance-search
