### ISSUE TITLE
Data Refresh job completes with failure due to sleeping database

### ISSUE THREAD

**Issue by zabeen** [Anthony-Nolan/Atlas#986] opened 2023-06-06 09:14 UTC
**Describe the bug**
If one of the databases is asleep at start of the data refresh job (usually the "dormant" matching db, when auto-pause is switched on), then the first attempt to scale up the db will fail due to a connection error. This is normal. However, the Sql exception should cause the data refresh request message to be replayed - by that that time (or several replays later), the db will have woken up, and data refresh can continue on unabated. Instead, the job is marked as completed, and a developer has to go in and manually restart the entire job with a new request (by which time, the db may have gone back to sleep again, and we face the same problem!).

**To Reproduce**
1. Submit a manual data refresh request to the matching algorithm functions app - note, the dormant db should be asleep before the job starts, which will be the case if there has been no other refresh jobs run recently (check auto-pause options for how long this takes).
2. Keep checking Application Insights or the data refresh table in the shared db for job progress.
3. When the job reaches the scaling up step, the job will fail - an alert message will be sent out, and a new "failed" message will be added to `completed-data-refresh-jobs` service bus topic, and the following error will be logged to AI:
"DATA REFRESH: Refresh failed. Exception: Microsoft.Data.SqlClient.SqlException (0x80131904): Database 'xxx-atlas-matching-X' on server 'xxx-atlas-sql-server.database.windows.net' is not currently available.  Please retry the connection later."

**Expected behaviour**
The refresh job request should automatically replay on db connection error, and not fail until all retries have been exhausted.

**Comment by DmitriyShcherbina** [comment] 2023-07-10 12:36
Unfortunatelly, it looks like this issue is still reproduces
<img width="697" alt="MicrosoftTeams-image (9)" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/cee59b91-d35f-4417-857c-c5eac26296bf">
<img width="677" alt="MicrosoftTeams-image (10)" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/d3af6a63-567f-4c0a-9b8c-4add99dfc93b">
<img width="434" alt="MicrosoftTeams-image (11)" src="https://github.com/Anthony-Nolan/Atlas/assets/107943429/ff91470a-1e40-499e-93f1-eb8238786c24">

**Comment by IgorKupreychik** [comment] 2023-07-11 05:54
@zabeen, PR with the fix is in the code review, please take a look when you have time. Please keep in mind that the whole fix is impossible to test locally, so that it can be fully tested only after deployment to Azure.

**Closed** 2023-07-12 09:15 UTC
Labels: bug, matching-algorithm

**Comment by DmitriyShcherbina** [comment] 2023-07-13 11:38
@zabeen @IgorKupreychik I've re-tested this ticket and data refresh hasn't been completed successfully


![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/0d3c8a78-d700-4a0c-8d90-0f8240f0c283)
![Image](https://github.com/Anthony-Nolan/Atlas/assets/107943429/d825f648-615a-4393-bb80-82078f0c231d)

Link to logs - https://portal.azure.com#@6f7ab052-989d-4dd8-b283-317f0a9b7b2c/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F6114522f-eea5-44ab-94ab-af37ffffc4d3%2FresourceGroups%2FDEV-ATLAS-RESOURCE-GROUP%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FDEV-ATLAS/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA11QO25CQQzsOYW1FUjLEeigJAVKHznLAC%252FSfmR7kyBxePweCZB045mxx3YvQy1kwgk6u1CfSnwnNHP0oFJXq3nziWIj%252BXWCgGqD8Oh7e%252BEMWq0o7HpZs%252FEOB4Geglur7CH0fiYbMtQ4N9pDkytN6geSPYT4b2KkwZBfz82RW5SPHkKJFfNfYQp9Wi5EKn86J8P9IJfVJLHNazfI9jY0BlpSiEMpkFzVfujFPdXRLWPtqxYdP3MF%252FCNZLjkBAAA%253D/timespan/2023-07-13T10%3A29%3A43.810Z%2F2023-07-13T11%3A29%3A43.810Z

**Comment by IgorKupreychik** [comment] 2023-07-13 12:02
@DmitriyShcherbina, wondering why do you think it's failed? In the logs I see 2 failed attempts, but there were no errors during the 3rd attempt and looks like it's still running (which makes me think the database is "awoke" and now refresh is doing its job... 
Request queue proves my assumption: the request is still in this queue which means it's still being processed.

![Image](https://github.com/Anthony-Nolan/Atlas/assets/24472823/66f978b6-80a0-4fda-97a9-739cb89cf1c0)


![Image](https://github.com/Anthony-Nolan/Atlas/assets/24472823/18c9aa5c-ceae-4c02-ad59-dad95dfb9dd9)

**Comment by IgorKupreychik** [comment] 2023-07-13 13:09
And finally the result


![Image](https://github.com/Anthony-Nolan/Atlas/assets/24472823/269e7e5d-3d64-4482-b1b6-aafaa5b1a94c)

**Comment by DmitriyShcherbina** [comment] 2023-07-13 13:17
@IgorKupreychik Oh, sorry. For some reason I decided that the process has stopped and the last "WasSuccessful" value was "null" and obviously I was wrong.
@zabeen So now result looks good, can we close this ticket or we need some additional data to check?

**Comment by zabeen** [comment] 2023-07-14 10:12
Thanks @DmitriyShcherbina and @IgorKupreychik , it all looks good now, many thanks!
