### ISSUE TITLE
Set 'IsAntigenMatch' when typing has no serology assignment in rel_dna_ser

### ISSUE THREAD

**Issue by RimkePostel** [Anthony-Nolan/Atlas#1073] opened 2023-09-21 14:44 UTC
**Title**
Currently no additional mismatch-information is provided for Dpb1 at the position level (MatchingResult.ScoringResult.ScoringResultsByLocus.Dpb1.ScoreDetailsAtPositionOne.IsAntigenMismatch and MatchingResult.ScoringResult.ScoringResultsByLocus.Dpb1.ScoreDetailsAtPositionTwo.IsAntigenMismatch). Therefore, we currently are unable to determine whether a DPB1 mismatch is an antigen or allele mismatch. This leads to a discrepancy between Hap-E and ATLAS (see screenshot)
![image](https://github.com/Anthony-Nolan/Atlas/assets/141727021/d183b5b0-03c4-4df3-9f7c-08878dd5fb53)

**Description**
Currently, the information at MatchingResult.ScoringResult.ScoringResultsByLocus.Dpb1.ScoreDetailsAtPositionOne.MatchGrade
and MatchingResult.ScoringResult.ScoringResultsByLocus.Dpb1.ScoreDetailsAtPositionTwo.MatchGrade does not provide us with enough information to determine whether a mismatch at the Dpb1 locus is a mismatch at the antigen or allele level. The 'IsAntigenMismatch' field currently always shows a 'NULL' value for DPB1. We would need to know if the value is a 'true' or 'false' for 'IsAntigenMismatch' to determine the mismatch type.

**Component(s) to enhance (if known)**
- Donor Import

**Business value (select one or more):**
- Improved user experience

**How would this enhancement provide this value?**
Provide additional information about mismatch at position level for the Dpb1 locus and show this in a similar fashion as Hap-E.

**Acceptance Criteria**

    Scenario: Determining mismatch class at DPB1 position level - antigen mismatch
        Given I have imported mismatch information for DPB1 at position level for a donor record
            When 'Matchgrade' is considered to be 'Mismatch'
            And 'IsAntigenMatch' is considered to be 'false'
            Then this position at the DPB1 locus is determined as 'antigen mismatch'

    Scenario: Determining mismatch class at DPB1 position level - allele mismatch
        Given I have imported mismatch information for DPB1 at position level for a donor record
            When 'Matchgrade' is considered to be 'Mismatch'
            And 'IsAntigenMatch' is considered to be 'true'
            Then this position at the DPB1 locus is determined as 'allele mismatch'

**Required By Date (if any)**
As we want to solve the discrepancies between Hap-E and ATLAS before UAT, preferably before Oct.

**Comment by zabeen** [comment] 2023-09-25 09:43
@RimkePostel is this an MVP issue?

**Comment by RimkePostel** [comment] 2023-09-25 10:04
@zabeen Yes, we consider this an MVP issue

**Comment by zabeen** [comment] 2023-09-28 18:33
@RimkePostel the reason Atlas is not indicating whether DPB1 alleles are antigen matched or not (i.e., `isAntigenMatch` is always `null`), is because none of the DPB1* alleles have any serology assignments within [rel_dna_ser](https://github.com/Anthony-Nolan/Atlas/files/12752769/rel_dna_ser-v3530-DPB1.txt). The only rows that do not have the `?` symbol are those with `0` due to being null expressing alleles.

I would need guidance from a search specialist on how antigen match status can be determined without such data.

**Comment by mmelchers** [comment] 2023-10-13 09:38
@zabeen we had a chat with the Hap-E engineers. Like you are saying there is no valid serology for DPB1. Therefore the isAntigenMatch should always be set to false in the search results generated by ATLAS. 

Since we have handling in place now, the urgency is down and is no longer needed for the MVP.

**Comment by zabeen** [comment] 2023-10-16 12:12
Thanks @mmelchers - to clarify the requirement:
For any locus (e.g., C, DPB1), when there is no `rel_dna_ser` serology metadata available for either the patient or donor typing, then `isAntigenMatch` should be set to `false` (instead of `null`, which is being done presently).

**Comment by mmelchers** [comment] 2023-10-17 07:49
@zabeen correct

**Comment by zabeen** [comment] 2023-11-20 19:07
### Testing
- Tested using the `Score` endpoint on matching algorithm functions app

- `C*01:02` and `01:11` are assigned to `C1` and belong to `01:03P`
- `C*12:02` and `12:112` have no assigned serology and belong to `12:02P`
- All DPB1* alleles lack serology assignments
- `DPB1*01:01` and `162:01` both belong to `01:01P`
- `DPB1*03:01` and `104:01` both belong to `03:01P`

#### C is matched
- HLA: `C*01:02,12:02` vs `C*01:11,12:112`
- Result: `"totalMatchCount": 2` and `"isAntigenMatch": true` at both positions

#### C is mismatched at position without ser assignment
- HLA: `C*01:02,12:02` vs `C*01:11,12:35`
- Result: `"totalMatchCount": 1`, `"isAntigenMatch": true` at matched position and `"isAntigenMatch": false` at mismatched position.

#### C is allele mismatched, antigen matched at position with ser assignment (regression test)
- HLA: `C*01:02,12:02` vs `C*01:10,12:112`
- Result: `"totalMatchCount": 1` and `"isAntigenMatch": true` at both positions.

#### C is mismatched at position with ser assignment (regression test)
- HLA: `C*01:02,12:02` vs `C*02:02,12:112`
- Result: `"totalMatchCount": 1`, `"isAntigenMatch": false` at mismatched position, and `"isAntigenMatch": true` at matched position.

#### C is mismatched at both positions
- HLA:  `C*01:02,12:02` vs `C*02:02,12:35`
- Result: `"totalMatchCount": 0` and `"isAntigenMatch": false` at both positions.

#### DPB1 is matched
- HLA: `DPB1*01:01,03:01` vs `DPB1*162:01,104:01`
- Result: `"totalMatchCount": 2` and `"isAntigenMatch": true` at both positions

#### DPB1 is mismatched at one position
- HLA: `DPB1*01:01,03:01` vs `DPB1*162:01,04:01`
- Result: `"totalMatchCount": 1`, `"isAntigenMatch": true` at matched position, and `"isAntigenMatch": false` at mismatched position.

#### DPB1 is mismatched at both positions
- HLA: `DPB1*01:01,03:01` vs `DPB1*02:01,04:01`
- Result: `"totalMatchCount": 0` and `"isAntigenMatch": false` at both positions.

**Closed by zabeen** 2023-11-20 19:07 UTC
Labels: scoring, wmda-uat
