### ISSUE TITLE
Investigate several failed searches in AN WMDA UAT environment

### ISSUE THREAD

**Issue by daria-sorokina-da** [Anthony-Nolan/Atlas#1031] opened 2023-08-09 11:42 UTC
Several searches failed in AN WMDA UAT environment according to the teams channel.

Need to investigate what happened.

Failures on Monday 7 Aug
Search ID: 441e824d-58fc-40a6-890a-8c45663f4dc1
Search ID: 5d7ea224-3a3d-4d5a-b945-eb7044aa06da
Search ID: 3d0e3c65-4553-422c-85b2-875fecf7e529
Search ID: 72b5c3ee-49f5-468a-8838-171ff382b1c4
Search ID: ad629ac1-4ae3-4e8e-80f1-a3ca72a5c61a

Failures on Tuesday 8 Aug
Search ID: e88331ba-b9a8-4ed2-995c-4dc2fcf36ffe

All failures have the following details:
Repeat ID (if relevant): 
Stage Reached: Matching Algorithm
ValidationError (if relevant):

**Comment by zabeen** [comment] 2023-08-11 11:15
### Investigations

#### Failures caused by *NEW allele in the patient
441e824d-58fc-40a6-890a-8c45663f4dc1
e88331ba-b9a8-4ed2-995c-4dc2fcf36ffe
db1bb854-59f5-46c1-a68d-d3cfed62e0a9
38dfe9cf-073e-4192-b5ef-2f631261a5fb

The validation error was reported in the search notification but logic app wasn't grabbing the value o report in teams, that's been fixed now.

#### Logs show only matching traces to phase 1, but no exceptions - search seem to be stopping after phase 1

3d0e3c65-4553-422c-85b2-875fecf7e529 - 07/08/2023 09:30
5d7ea224-3a3d-4d5a-b945-eb7044aa06da - 07/08/2023 09:30
72b5c3ee-49f5-468a-8838-171ff382b1c4 - 07/08/2023 09:37
ad629ac1-4ae3-4e8e-80f1-a3ca72a5c61a - 07/08/2023 09:40
5bad2ac4-ea2d-4872-aef5-14c28010393c - 09/08/2023 14:18
d6a71944-a4e2-4243-b731-cd6db2711bfd - 11/08/2023 07:00
9432ab74-4d94-4001-8e98-69ae45ef02a2 - 11/08/2023 07:02

Possible thread pool starvation and high CPU usage reported by UAT-WMDA-ATLAS-FUNCTIONS. It's possible that match prediction is using up the CPU/threads on the app service plan and preventing matching phase 2 from completing??

@seanmobrien @daria-sorokina-da @luken-an  would appreciate your insights.

**Comment by zabeen** [comment] 2023-08-11 13:50
### Investigations - Part 2

#### Attempt 1
- `MATCHING_MAX_CONCURRENT_PROCESSES_PER_INSTANCE` reduced from 3 to 2
- `MAX_CONCURRENT_ACTIVITY_FUNCTIONS` reduced from 5 to 3
- Re-ran 25 searches from 7th August 2023 08:00-09:00 UTC in one batch
- Early matching algorithm logs show only 2 matching requests being processed in parallel, as expected

**Comment by zabeen** [comment] 2023-08-14 09:23
### Dev
- Add `WillRetry` to metadata of search notification
- Add search request and attempt number to log (for both successful and failed searches)

**Comment by zabeen** [comment] 2023-09-06 14:48
@seanmobrien increased the number of vCores on the active matching db from 8 to 20, and that has reduced the number of failed searches at the matching stage, but not completely eliminated them. The same issue has not yet been observed in live-wmda-atlas, so there is a still a question of whether any action needs to be taken beyond tweaking resource configurations and reducing search parallelisation on UAT as much as possible.

**Closed** 2023-10-16 12:31 UTC
Labels: investigation, performance-search
