### ISSUE TITLE
Set up full system tests infrastructure

### ISSUE THREAD

**Issue by benbelow** [Anthony-Nolan/Atlas#738] opened 2022-04-13 15:39 UTC
The core algorithms' logic is tested in individual test suites. 

It would be good to have some full system tests that cover orchestration of a full search request, including internal service bus messaging and output file writing.

**Comment by zabeen** [comment] 2023-12-20 15:42
Duplicate of #1158

**Closed** 2023-12-20 15:44 UTC
Labels: automated-tests
